### PR TITLE
Feature/convert

### PR DESCRIPTION
**Pull request by catalino-dev**
## Status
**READY**

## Description
Added:
- DEG (degrees) `Math.toDegrees(double angRad)`
- RAD (radians) `Math.toRadians(double angDeg)`
- ABS (absolute) `Math.abs(double a)`

## Todos
**TESTS**
- [x] DEG
- [x] RAD
- [x] ABS

## Steps to Test
```sh
javac CalculateAction.java
java Calculate deg/rad/abs <number_to_test>
```

### CODE REVIEW

**Comment by sbanjoe25** [comment]
Okay, seems all good for me here.  :+1: 
DEG, RAD and ABS are working fine.

**Review by sbanjoe25 — APPROVED** [review]
All things are looking good.

**Review by stevenJhonGil — COMMENTED** [review]
With regards to your second java class CalculateMethod.java, how come you don't have any conflict where in the develop branch has it renamed into CalculateAction.java?

Other than that, everything looks fine (y)

**Comment by stevenJhonGil** [comment]
Also in your documentation, README.md... It lacks this

## Requirements
- JDK 8

Kindly check in the develop branch

**Comment by sbanjoe25** [comment]
Yes, I agree with @stevenJhonGil. Your README.md is missing the requirements specs. Please update it and this branch is ready to merge.

**Pull request closed without merging**
