### PR TITLE
Feature/exponents

### PR DESCRIPTION
**Pull request by kenichigouang**
Added pow, square root, and cube root methods.

- [x] pow (b, e)
- [x] sqrt (a)
- [x] cbrt (a)

### CODE REVIEW

**Review by sbanjoe25 — CHANGES_REQUESTED** [review]
Please resolve conflicts.

**Comment by michaelcapuno** [comment]
has merge conflict

**Review by michaelcapuno — COMMENTED** [review]
has conflicts with base branch

**Comment by sbanjoe25** [comment]
Kindly check and resolve conflicts

**Comment by kenichigouang** [comment]
@sbanjoe25 @michaelcapuno Hi guys. Resolved conflicts. Please review the rest. Thanks.

**Comment by sbanjoe25** [comment]
Alright, seems all good on my end. :+1:

**Review by sbanjoe25 — APPROVED** [review]
:100: :+1: good to merge

**Review by michaelcapuno — APPROVED** [review]

**Comment by kana-ph** [comment]
@kenichigouang 

Please add root function:

```bash
$ java Compute root 27 3
3
```

Reference: http://stackoverflow.com/questions/6325793/nth-root-implementation#6325814

**Comment by kenichigouang** [comment]
@sbanjoe25 @michaelcapuno Hi guys. Added a new method to get the nth root of a positive number.

*High precision was intentionally not accounted for due to the use of the double data type (e.g. 2 root of 2 = 1.99999...)

**Comment by sbanjoe25** [comment]
@kenichigouang  so I checkout your branch and tested it on my end. So far, all results are correct. Nice :+1:

**Comment by michaelcapuno** [comment]
@kenichigouang tested your updated code and it's seems to be good. :+1:

**Pull request merged**
